### ISSUE TITLE
elasticsearch memory limits

### ISSUE THREAD

**Issue by themantalope** [jina-ai/executor-elasticsearch-indexer#14]
Hi everyone,

Just an FYI with the example docker-compose file, there is no limit set on how much memory elasticsearch should use. On my machine (with 64GB of ram), the container natively consumed ~32GB of RAM, which would probably cause most home systems to crash.

Would recommend using something like:
```yaml
version: "3.3"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
    networks:
      - elastic
    mem_limit: 4g

networks:
  elastic:
    name: elastic

```

Where the `ES_JAVA_OPTS` limits the memory usage.
